[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "opcclient"
version = "0.1.0"
description = "A Python client for OPC communication"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
dependencies = [
    "opcua>=0.98.13",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "mypy>=1.0.0",
    "ruff>=0.0.1",
]

[tool.hatch.build.targets.wheel]
packages = ["opcclient"]

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
target-version = "py38"
select = ["E", "F", "B", "I"]
